---
dist: trusty
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true

matrix:
  include:
    - env: TAG=2.3  # 2.3.x bugs and security
    - env: TAG=2.4  # 2.4.x bugs and security
    - env: TAG=2.5  # 2.4.x bugs and security
    - env: TAG:2.6  # Development

services:
  - docker

addons:
  apt:
    sources:
      - docker-trusty
    packages:
      - docker-ce

script:
  - echo $DOCKER_HOST
  - docker run --net=host -it -v $(pwd):/data/$(basename ~+) -w /data/$(basename ~+) \
    lansible/ansible-dev-container:$TAG molecule converge

notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
