---
- block:
    - name: Link init script for older ubuntu versions
      file:
        src: "{{ tautulli_install_location }}/init-scripts/init.ubuntu"
        dest: /etc/init.d/tautulli
        mode: 0755
        state: link

    - name: Set defaults in file
      template:
        src: tautulli/ubuntu-tautulli-defaults.j2
        dest: /etc/default/tautulli

    - name: Autostart Tautulli and restart service
      service:
        name: tautulli
        enabled: true
      notify: restart tautulli

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 15.10
