---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: lxd

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: tautulli-CentOS7
    alias: centos/7/amd64

  - name: tautulli-Debian9
    alias: debian/stretch/amd64

  - name: tautulli-Debian8
    alias: debian/jessie/amd64

#  - name: tautulli-Fedora27
#    alias: fedora/27/amd64

#  - name: tautulli-Fedora26
#    alias: fedora/26/amd64

  - name: tautulli-Ubuntu1604
    alias: ubuntu/xenial/amd64

  - name: tautulli-Ubuntu1404
    alias: ubuntu/trusty/amd64

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

verifier:
  name: goss
  lint:
    name: yamllint
    options:
      config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

scenario:
  name: default
